Repository luminartech/uds_protocol, pull requests merged in 2025-09, with the labels that each got.

#24 docs: Add description to Cargo.toml files
  Cargo.toml
  uds_protocol_derive/Cargo.toml
Labels: documentation

#26 Add codecov.io test reports to uds_protocol
  .config/nextest.toml
  .github/workflows/ci.yml
  README.md
  uds_protocol_derive/README.md
Labels: documentation, enhancement

#29 Fixes to allow for HIL testing
  Cargo.toml
  src/common/diagnostic_identifier.rs
  src/common/diagnostic_session_type.rs
  src/protocol_definitions.rs
Labels: bug

#31 Place Serde Derive behind feature flag
  Cargo.lock
  Cargo.toml
  src/common/active_diagnostic_session.rs
  src/common/bcd_4_byte.rs
  src/common/communication_control_type.rs
  src/common/communication_type.rs
  src/common/diagnostic_identifier.rs
  src/common/diagnostic_session_type.rs
  src/common/dtc_ext_data.rs
  src/common/dtc_snapshot.rs
  src/common/dtc_status.rs
  src/common/format_identifiers.rs
  src/common/negative_response_code.rs
  src/common/reset_type.rs
  src/common/security_access_type.rs
  src/common/suppressable_positive_response.rs
  src/error.rs
  src/lib.rs
  src/protocol_definitions.rs
  src/request.rs
  src/response.rs
  src/service.rs
  src/services/clear_dtc_information.rs
  src/services/communication_control.rs
  src/services/control_dtc_settings.rs
  src/services/diagnostic_session_control.rs
  src/services/ecu_reset.rs
  src/services/negative_response.rs
  src/services/read_data_by_identifier.rs
  src/services/read_dtc_information.rs
  src/services/request_download.rs
  src/services/request_file_transfer.rs
  src/services/routine_control.rs
  src/services/security_access.rs
  src/services/tester_present.rs
  src/services/transfer_data.rs
  src/services/write_data_by_identifier.rs
  src/traits.rs
  uds_protocol_derive/src/lib.rs
Labels: enhancement
